# Generated by Django 4.1.3 on 2022-11-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Your Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='data', max_length=254),
            preserve_default=False,
        ),
    ]
